import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('agent_devices', (t) => {
    t.increments('id').primary();

    // Unique machine identifier (UUID generated by the agent on first run)
    t.string('uuid', 64).notNullable().unique();

    t.string('hostname', 255).notNullable();
    t.string('ip', 45).nullable();
    t.jsonb('os_info').nullable();            // { platform, distro, release, arch }
    t.string('agent_version', 32).nullable(); // version string reported by agent

    // Which API key was used to register this device (null if key deleted)
    t.integer('api_key_id')
      .unsigned()
      .nullable()
      .references('id')
      .inTable('agent_api_keys')
      .onDelete('SET NULL');

    t.string('status', 16).notNullable().defaultTo('pending'); // pending|approved|refused

    // Config pushed back to the agent in each push response
    t.integer('check_interval_seconds').notNullable().defaultTo(60);

    // Approval tracking
    t.integer('approved_by')
      .unsigned()
      .nullable()
      .references('id')
      .inTable('users')
      .onDelete('SET NULL');
    t.timestamp('approved_at').nullable();

    // Optional agent group assignment
    t.integer('group_id')
      .unsigned()
      .nullable()
      .references('id')
      .inTable('monitor_groups')
      .onDelete('SET NULL');

    t.timestamps(true, true);

    t.index('status');
    t.index('api_key_id');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('agent_devices');
}
