#!/bin/bash
# build-mac.sh — Build Obliview.app for macOS
# Run from the desktop-app/ directory: ./build-mac.sh
#
# To release a new version:
#   1. Edit desktop-app/VERSION  (e.g. 1.2.0)
#   2. Run this script — the version is injected everywhere automatically.
set -e

BINARY="obliview"
APPNAME="Obliview"
BUNDLE="$APPNAME.app"
WEBP="../client/public/logo.webp"
PNG="logo.png"   # generated by build-windows.ps1 and committed to repo

# ── Read version (single source of truth) ────────────────────────────────────
if [ ! -f VERSION ]; then
  echo "ERROR: VERSION file not found in $(pwd)."
  exit 1
fi
VERSION=$(cat VERSION | tr -d '[:space:]')
if [ -z "$VERSION" ]; then
  echo "ERROR: VERSION file is empty."
  exit 1
fi
echo "  Version: $VERSION"

# ── Step 1: Ensure logo.png exists for go:embed ──────────────────────────────
echo "=== Step 1: Checking logo.png for go:embed ==="
if [ ! -f "$PNG" ]; then
  echo "  logo.png not found — generating from logo.webp via sips..."
  if ! sips -s format png "$WEBP" --out "$PNG" 2>/dev/null; then
    echo "ERROR: Could not convert logo.webp to PNG."
    echo "  • On macOS 12+: sips supports WebP natively."
    echo "  • Alternatively: brew install imagemagick && magick $WEBP $PNG"
    exit 1
  fi
fi
echo "  OK: $PNG ($(wc -c < "$PNG" | tr -d ' ') bytes)"

# ── Step 2: Build the Go binary ───────────────────────────────────────────────
echo "=== Step 2: Building Go binary ==="
# No -H flag needed on macOS — the .app bundle handles the GUI/console distinction.
# -X main.appVersion injects the version string so React can detect outdated clients.
CGO_ENABLED=1 go build -ldflags "-X main.appVersion=$VERSION" -o "$BINARY" .
echo "  Built: $BINARY ($(du -sh "$BINARY" | cut -f1))"

# ── Step 3: Create .app bundle structure ─────────────────────────────────────
echo "=== Step 3: Creating $BUNDLE ==="
rm -rf "$BUNDLE"
mkdir -p "$BUNDLE/Contents/MacOS"
mkdir -p "$BUNDLE/Contents/Resources"

cp "$BINARY" "$BUNDLE/Contents/MacOS/$BINARY"

# ── Step 4: Info.plist ───────────────────────────────────────────────────────
echo "=== Step 4: Writing Info.plist ==="
cat > "$BUNDLE/Contents/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key>
  <string>me.binaryhearts.obliview</string>
  <key>CFBundleName</key>
  <string>Obliview</string>
  <key>CFBundleDisplayName</key>
  <string>Obliview</string>
  <key>CFBundleExecutable</key>
  <string>obliview</string>
  <key>CFBundleIconFile</key>
  <string>AppIcon</string>
  <key>CFBundleVersion</key>
  <string>$VERSION</string>
  <key>CFBundleShortVersionString</key>
  <string>$VERSION</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSHumanReadableCopyright</key>
  <string>Copyright © 2025 BinaryHearts</string>
  <key>LSMinimumSystemVersion</key>
  <string>10.13</string>
  <!-- Allows the webview to load http:// URLs during first-run setup -->
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
</dict>
</plist>
EOF

# ── Step 5: Generate .icns from logo.png ─────────────────────────────────────
echo "=== Step 5: Generating AppIcon.icns ==="
ICONSET="AppIcon.iconset"
rm -rf "$ICONSET"
mkdir "$ICONSET"

# macOS requires these exact filenames in the iconset
for size in 16 32 128 256 512; do
  double=$((size * 2))
  sips -z $size   $size   "$PNG" --out "$ICONSET/icon_${size}x${size}.png"    2>/dev/null
  sips -z $double $double "$PNG" --out "$ICONSET/icon_${size}x${size}@2x.png" 2>/dev/null
done

iconutil -c icns "$ICONSET" -o "$BUNDLE/Contents/Resources/AppIcon.icns"
rm -rf "$ICONSET"
echo "  Built: $BUNDLE/Contents/Resources/AppIcon.icns"

# ── Step 6: Zip into dist/Obliview.zip for distribution ──────────────────────
echo "=== Step 6: Creating dist/Obliview.zip ==="
mkdir -p dist
rm -f dist/Obliview.zip
# ditto preserves macOS metadata and resource forks correctly (better than zip)
ditto -c -k --sequesterRsrc --keepParent "$BUNDLE" dist/Obliview.zip
echo "  Zipped: dist/Obliview.zip ($(du -sh dist/Obliview.zip | cut -f1))"

# ── Step 7: Create drag-to-Applications DMG (with custom background) ──────────
echo "=== Step 7: Creating dist/Obliview.dmg ==="

DMG_STAGING="__dmg_staging__"
DMG_TMP="__tmp_obliview_rw.dmg"
DMG_OUT="dist/Obliview.dmg"
BACKGROUND="build/dmg-background.png"   # 540×380 px PNG supplied by user

# DMG window geometry (must match background image dimensions)
WIN_W=540
WIN_H=380
WIN_LEFT=200
WIN_TOP=120
WIN_RIGHT=$((WIN_LEFT + WIN_W))
WIN_BOTTOM=$((WIN_TOP + WIN_H))

# Icon positions inside the window
ICON_SIZE=128
APP_X=160
APP_Y=190
APPS_X=380
APPS_Y=190

# ── Prepare staging folder ────────────────────────────────────────────────────
rm -rf "$DMG_STAGING"
mkdir "$DMG_STAGING"
cp -R "$BUNDLE" "$DMG_STAGING/"
ln -s /Applications "$DMG_STAGING/Applications"

rm -f "$DMG_OUT" "$DMG_TMP"

# ── Create writable DMG (no -fsargs → compatible with macOS 12+) ─────────────
hdiutil create \
  -srcfolder "$DMG_STAGING" \
  -volname "$APPNAME" \
  -format UDRW \
  -o "$DMG_TMP"

# ── Mount RW DMG ──────────────────────────────────────────────────────────────
MOUNT_POINT=$(hdiutil attach -readwrite -noverify -noautoopen "$DMG_TMP" \
  | awk '/\/Volumes\//{print $NF}')

if [ -z "$MOUNT_POINT" ]; then
  echo "ERROR: Could not mount DMG"
  rm -f "$DMG_TMP"
  rm -rf "$DMG_STAGING"
  exit 1
fi
echo "  Mounted at: $MOUNT_POINT"

# ── Copy background image (hidden folder inside the DMG) ─────────────────────
if [ -f "$BACKGROUND" ]; then
  mkdir -p "$MOUNT_POINT/.background"
  cp "$BACKGROUND" "$MOUNT_POINT/.background/background.png"
  echo "  Copied background: $BACKGROUND"
  BG_APPLESCRIPT="set background picture of viewOptions to file \".background:background.png\""
else
  echo "  WARNING: $BACKGROUND not found — DMG will have no custom background."
  echo "           Create a 540×380 PNG at desktop-app/build/dmg-background.png"
  BG_APPLESCRIPT="-- no background"
fi

# ── AppleScript: layout the Finder window ─────────────────────────────────────
osascript <<APPLESCRIPT
tell application "Finder"
  tell disk "$APPNAME"
    open
    set current view of container window to icon view
    set toolbar visible of container window to false
    set statusbar visible of container window to false
    set bounds of container window to {$WIN_LEFT, $WIN_TOP, $WIN_RIGHT, $WIN_BOTTOM}
    set viewOptions to the icon view options of container window
    set arrangement of viewOptions to not arranged
    set icon size of viewOptions to $ICON_SIZE
    $BG_APPLESCRIPT
    set position of item "$BUNDLE" to {$APP_X, $APP_Y}
    set position of item "Applications" to {$APPS_X, $APPS_Y}
    close
    open
    update without registering applications
    delay 2
    close
  end tell
end tell
APPLESCRIPT

# ── Sync, unmount, convert to read-only compressed DMG ───────────────────────
sync
hdiutil detach "$MOUNT_POINT" -quiet

hdiutil convert "$DMG_TMP" \
  -format UDZO \
  -imagekey zlib-level=9 \
  -o "$DMG_OUT"

rm -f "$DMG_TMP"
rm -rf "$DMG_STAGING"

echo "  Created: $DMG_OUT ($(du -sh "$DMG_OUT" | cut -f1))"

# ── Step 8: Summary ───────────────────────────────────────────────────────────
echo ""
echo "=== Done! ==="
echo "  Bundle:  $BUNDLE"
echo "  Zip:     dist/Obliview.zip"
echo "  DMG:     dist/Obliview.dmg"
du -sh "$BUNDLE" dist/Obliview.zip dist/Obliview.dmg
echo ""
echo "To run:   open $BUNDLE"
echo "To share: distribute dist/Obliview.dmg (drag-to-Applications installer)"
echo ""
echo "NOTE: If macOS blocks the app (Gatekeeper) because it is unsigned:"
echo "  Right-click → Open  (first time only)"
echo "  or: xattr -dr com.apple.quarantine $BUNDLE"
